name: umatter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.9
  flutter_svg: ^1.0.3
  flutterfire_ui: ^0.3.4
  get: ^4.6.1
  google_fonts: ^2.3.1
  intl: ^0.17.0
  lottie: ^1.2.1
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.18

dev_dependencies:
  audioplayers: ^0.20.1
  cloud_firestore: ^3.1.8
  firebase: ^9.0.2
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  google_sign_in: ^5.2.3
  share_plus: ^3.0.4
  syncfusion_flutter_charts: ^19.4.53

flutter:
  uses-material-design: true

  assets:
    - assets/img/onboarding/
    - assets/img/home_page/
    - assets/img/directories/
    - assets/img/
    - assets/icons/
    - assets/icons/json/
    - assets/terms_of_use/
    - assets/audio/
    - assets/
