name: umatter
# description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^1.0.3
  flutter_swiper: ^1.1.6
  flutter_tts: ^3.3.3
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.3.1
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  lottie: ^1.2.1
  percent_indicator: ^4.0.0
  shared_preferences: ^2.0.13
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.18

dev_dependencies:
  audioplayers: ^0.20.1
  cloud_firestore: ^3.1.8
  firebase: ^9.0.2
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  get: ^4.6.5
  google_sign_in: ^5.2.3
  share_plus: ^3.0.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/umatter.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/umatter.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - json/

    - assets/img/

    - assets/icons/

    - assets/icons/json/

    - assets/terms_of_use/

    - assets/audio/

    - assets/audio/acoustic/
    - assets/audio/instrumental/
    - assets/audio/lofi/
    - assets/audio/piano/

    - assets/img/assessment/
    - assets/img/home_page/
    - assets/img/onboarding/
    - assets/img/authentication/
    - assets/img/music_therapy/
    - assets/img/diary/
    - assets/img/discover/
    - assets/img/professionals/
    - assets/img/professionals/colleges_logo/
